---
title: "data analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      comment = "#>"
                      )
```

---

## Study sites

```{r}
readd(Q10_map)
```

How many datapoints?
```{r}
readd(study_summary)$datapoints %>% knitr::kable()
```

How many studies?
```{r}
readd(study_summary)$study_counts %>% knitr::kable()
```


---

## Field vs. lab 

### Stats

CO2 - by temperature
```{r}
readd(Q10_stats)$co2_aov_temp
```

paired (field AND lab) results were not available for < 0 C and 0-5 C.


CO2 - across all temperatures

- ANOVA
```{r}
readd(Q10_stats)$co2_aov_all
```

- LME
```{r}
readd(Q10_stats)$co2_lme_all
```

N2O - across all temperatures
```{r}
readd(Q10_stats)$n2o_aov_all
```

CH4 - across all temperatures
```{r}
readd(Q10_stats)$ch4_aov_all
```


### Graphs

```{r}
readd(Q10_graphs)
```


---

<details>   
   <summary>Session Info</summary>
   
Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details> 